### ISSUE TITLE
rtorrent.rc

### ISSUE THREAD

**Issue by tocks53** [drgroot/docker-rtorrent#1]
Hello,
thank for your docker, but when i run the docker.

It dont create the rtorrent.rc in /config

**Comment by drgroot** [comment]
it wont create one. you will need to provide one. see the example in config/rtorrent.rc

**Comment by drgroot** [comment]
Planned feature

**Comment by dogboy23** [comment]
Hi again... is this feature meant to copy the .rtorrent.rc file in /config into the home folder?

It is a good idea, but I had to copy it across...

Thanks

**Comment by drgroot** [comment]
Currently if you have a file `rtorrent.rc` in the /config folder, it is symbolically linked to `/root/.rtorrent.rc`
However, if one doesn't have a /config folder, this will not work. So hopefully later this week I'm going to work on some new features

1. use `/config/rtorrent.rc` or `/config/.rtorrent.rc` if present (priority on `rtorrent.rc`
2. if /config not present, use some default `.rtorrent.rc`
3. if /config is present but not `(.)?rtorrent.rc` file, create a default file

what do you think?

**Comment by dogboy23** [comment]
I just noticed it needs to not have "." Prefix. I will try again.

I think thisi s a great method!

Nick
-- 
Nick Diacre
T: 07766 754 755
w: http://www.ddld.uk

**Comment by drgroot** [comment]
this will be merged with #6
