### ISSUE TITLE
migrating existing rutorrent session

### ISSUE THREAD

**Issue by dogboy23** [drgroot/docker-rtorrent#11]
worth adding additional volume mount point for the` ~/.session/` folder. I used `/session/`

This allowed me to import my own previous torrent list

**Comment by drgroot** [comment]
true. will look into today for sure

**Comment by dogboy23** [comment]
to be fair it doesn't massively affect the image, it can be done by the user easily enough

**Comment by drgroot** [comment]
True, but it might be a nice option. I mean its literally one line of code for me to add, I just want to test it to make sure nothing breaks.

**Comment by drgroot** [comment]
seems to work after testing merge #14
