### ISSUE TITLE
openvpn config

### ISSUE THREAD

**Issue by dogboy23** [drgroot/docker-rtorrent#2]
Hi, trying to get this working with openvpn, I drop my ovpn file into a linked vpn folder, but i get the following error:

```
Sun Mar 27 23:02:26 2016 OpenVPN 2.3.7 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [EPOLL] [MH] [IPv6] built on Jul 10 2015
stdout
23:02:26
Sun Mar 27 23:02:26 2016 library versions: OpenSSL 1.0.2d 9 Jul 2015, LZO 2.09
stdout
23:02:26
Sun Mar 27 23:02:26 2016 Control Channel Authentication: tls-auth using INLINE static key file
stdout
23:02:26
Sun Mar 27 23:02:26 2016 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
stdout
23:02:26
Sun Mar 27 23:02:26 2016 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
stdout
23:02:26
Sun Mar 27 23:02:26 2016 Socket Buffers: R=[87380-&gt;131072] S=[16384-&gt;131072]
stdout
23:02:26
Sun Mar 27 23:02:26 2016 Attempting to establish TCP connection with [AF_INET]94.229.74.90:443 [nonblock]
stdout
23:02:27
Sun Mar 27 23:02:27 2016 TCP connection established with [AF_INET]94.229.74.90:443
stdout
23:02:27
Sun Mar 27 23:02:27 2016 TCPv4_CLIENT link local: [undef]
stdout
23:02:27
Sun Mar 27 23:02:27 2016 TCPv4_CLIENT link remote: [AF_INET]94.229.74.90:443
stdout
23:02:27
Sun Mar 27 23:02:27 2016 TLS: Initial packet from [AF_INET]94.229.74.90:443, sid=239cf534 a337149e
stdout
23:02:28
Sun Mar 27 23:02:28 2016 VERIFY OK: depth=1, C=IT, ST=IT, L=Perugia, O=airvpn.org, CN=airvpn.org CA, emailAddress=info@airvpn.org
stdout
23:02:28
Sun Mar 27 23:02:28 2016 Validating certificate key usage
stdout
23:02:28
Sun Mar 27 23:02:28 2016 ++ Certificate has key usage  00a0, expects 00a0
stdout
23:02:28
Sun Mar 27 23:02:28 2016 VERIFY KU OK
stdout
23:02:28
Sun Mar 27 23:02:28 2016 Validating certificate extended key usage
stdout
23:02:28
Sun Mar 27 23:02:28 2016 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
stdout
23:02:28
Sun Mar 27 23:02:28 2016 VERIFY EKU OK
stdout
23:02:28
Sun Mar 27 23:02:28 2016 VERIFY OK: depth=0, C=IT, ST=IT, L=Perugia, O=airvpn.org, CN=server, emailAddress=info@airvpn.org
stdout
23:02:29
Sun Mar 27 23:02:29 2016 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
stdout
23:02:29
Sun Mar 27 23:02:29 2016 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
stdout
23:02:29
Sun Mar 27 23:02:29 2016 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
stdout
23:02:29
Sun Mar 27 23:02:29 2016 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
stdout
23:02:29
Sun Mar 27 23:02:29 2016 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
stdout
23:02:29
Sun Mar 27 23:02:29 2016 [server] Peer Connection Initiated with [AF_INET]94.229.74.90:443
stdout
23:02:31
Sun Mar 27 23:02:31 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
stdout
23:02:31
Sun Mar 27 23:02:31 2016 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 10.5.0.1,comp-lzo no,route-gateway 10.5.0.1,topology subnet,ping 10,ping-restart 60,ifconfig 10.5.3.130 255.255.0.0'
stdout
23:02:31
Sun Mar 27 23:02:31 2016 OPTIONS IMPORT: timers and/or timeouts modified
stdout
23:02:31
Sun Mar 27 23:02:31 2016 OPTIONS IMPORT: LZO parms modified
stdout
23:02:31
Sun Mar 27 23:02:31 2016 OPTIONS IMPORT: --ifconfig/up options modified
stdout
23:02:31
Sun Mar 27 23:02:31 2016 OPTIONS IMPORT: route options modified
stdout
23:02:31
Sun Mar 27 23:02:31 2016 OPTIONS IMPORT: route-related options modified
stdout
23:02:31
Sun Mar 27 23:02:31 2016 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
stdout
23:02:31
Sun Mar 27 23:02:31 2016 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
stdout
23:02:31
Sun Mar 27 23:02:31 2016 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
stdout
23:02:31
Sun Mar 27 23:02:31 2016 Exiting due to fatal error
stdout
23:02:46
ifconfig: tun0: error fetching interface information: Device not found
```

Any idea how to fix this? Help much appreciated. This running docker on a synology rs3412xs, DSM 6.0, privileged. As far as I can tell from within Busybox, /dev/net and /dev/net/tun do not exist. I have tried:

mkdir /dev/net/
mknod /dev/net/tun c 10 200

followed by:

openvpn --config *.ovpn,

but it throws the same error...

Any idea what I am doing wrong?

Thanks

Nick

**Comment by drgroot** [comment]
Right away I can tell you a few things (I've run into the same issue)

1. You need to enable the tap/tun module on Synology for VPN connections.
So the host needs to have tap/tun enabled.
This has to be done using command line (so run `insmod /lib/modules/tun.ko`)

2. For the docker container to be able to use the tun module on the host, you need to run the container with elevated permissions. I can't remember how to do this exactly. But if you stop the container and click _edit_, I know there is a setting somewhere. I will get exact instructions for that later. At work ATM. :D

**Comment by dogboy23** [comment]
Thanks for the reply. Didn't even think about that, will look at that when
I'm back in front of it.

I will update you :)

On 28 March 2016 at 12:56:04, yusuf ali (notifications@github.com) wrote:

> Right away I can tell you a few things (I've run into the same issue)
>
>    1.
>
>    You need to enable the tap/tun module on Synology for VPN connections.
>    So the host needs to have tap/tun enabled.
>    This has to be done using command line (so run insmod
>    /lib/modules/tun.ko)
>    2.
>
>    For the docker container to be able to use the tun module on the host,
>    you need to run the container with elevated permissions. I can't remember
>    how to do this exactly. But if you stop the container and click *edit*,
>    I know there is a setting somewhere. I will get exact instructions for that
>    later. At work ATM. :D
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/drgroot/docker-rtorrent/issues/2#issuecomment-202355016>
>
-- 
Nick Diacre
T: 07766 754 755
w: http://www.ddld.uk

**Comment by dogboy23** [comment]
That command made it work instantly, is there anyway of ensuring it is
persistent through reboots/updates?

Nick

**Comment by dogboy23** [comment]
And now I have it working, I wondered of the possibility of using/installing plugins and where is the correct location in the container

TIA

Nick

**Comment by drgroot** [comment]
I usually create a startup script on synology that does it. On DSM v6 there is a startup option using a triggered script that I use to automatically enable tun/tap.

**Comment by dogboy23** [comment]
I'm using DSM 6.0, I can see where to put the triggered task etc, just being a noob, I am not 100% on the code the script should contain, I'm pretty sure it's more than just  `insmod /lib/modules/tun.ko`

**Comment by drgroot** [comment]
no your correct. that is all it should have
i mean you could have the script like this to work independant of default shell (ash, sh etc.)
```
/usr/bin/env insmod /lib/modules/tun.ko
```
But I think that's overkill as it should work regardless.
