### ISSUE TITLE
broken somehow...

### ISSUE THREAD

**Issue by dogboy23** [drgroot/docker-rtorrent#5]
I started again this evening with a new image, tried both latest and vertigo, neither seemed to work anymore, despite repeating everything from yesterday. I just wanted a clean start and to create a volume link for the plugins and session, but I've not even managed to get that far.

rtorrent is running fine, and the VPN is connected fine.

error message in rutorrent webpage is:

`torrent list not yet available, connection to rtorrent not established`

and

`[29.03.2016 21:50:25] Bad response from server: (0 [error,getplugins]) Error: NETWORK_ERR: XMLHttpRequest Exception 101`
`[29.03.2016 21:50:25] Bad response from server: (0 [error,getuisettings])`

I have tried using the /config/rtorrent.rc volume approach, I've also manually copying a file over to ~/.rtorrent.rc

the .rtorrent.rc file is the vanilla file used, text pulled from github.

Has the image changed at all since last night?

Thanks in advance

**Comment by dogboy23** [comment]
ummm, so that was a cache issue, cleared the cache and I no longer get that page, however unable to connect to rutorrent...

harder to trouble shoout I guess...

**Comment by drgroot** [comment]
merged to #6
