### ISSUE TITLE
rutorrent interface not running

### ISSUE THREAD

**Issue by dogboy23** [drgroot/docker-rtorrent#6]
no access to web interface, only processes running are /bin/sh, rtorrent, busybox, top when I run top.

Nick

**Comment by drgroot** [comment]
try the build implemented after #7 
so try the tag "develop" on the docker hub

**Comment by drgroot** [comment]
i tested it and it seems to work #8

it creates a rtorrent config file if one does not exist
seems to fix the lighttpd issue you were having by creating the files and give the user the correct perms

**Comment by dogboy23** [comment]
resolved... had some issues initially with having my own config  file in /config, but when I deleted it and used the created one it was fine.
